# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75c86e9c3e95ddfb828b411ba0d31f7fb77a0cb86844310e54393c9e5ac115237c8436e4e742e51f82b8dd6dab6c8676a57ae495707c3c778c1c3571c2e25f2

test:
  secret_key_base: 374b7d6f0d79b727e9d8034e0eddec72d3fdc0cb6317e09b4e3704a8c2c0fbaf7ed4175e70756da3ec8df7b1de90eb106ba1e2e19c3a8eeaa294a6d7b60429ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
